# Generated by Django 4.2.16 on 2025-12-01 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PingLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("endpoint", models.CharField(help_text="The endpoint that was pinged", max_length=255)),
                ("method", models.CharField(help_text="HTTP method used", max_length=10)),
                ("status_code", models.IntegerField(help_text="HTTP status code returned")),
                ("response_time_ms", models.FloatField(help_text="Response time in milliseconds")),
                ("success", models.BooleanField(help_text="Whether the ping was successful")),
                (
                    "error_message",
                    models.TextField(blank=True, help_text="Error message if ping failed", null=True),
                ),
                (
                    "request_headers",
                    models.JSONField(blank=True, default=dict, help_text="Request headers sent"),
                ),
                (
                    "response_headers",
                    models.JSONField(blank=True, default=dict, help_text="Response headers received"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="When the ping was performed"),
                ),
            ],
            options={
                "verbose_name": "Ping Log",
                "verbose_name_plural": "Ping Logs",
                "db_table": "ping_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SystemHealth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "service_name",
                    models.CharField(help_text="Name of the service being checked", max_length=100),
                ),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("database", "Database"),
                            ("redis", "Redis"),
                            ("external_api", "External API"),
                            ("file_system", "File System"),
                        ],
                        help_text="Type of service being checked",
                        max_length=20,
                    ),
                ),
                ("is_healthy", models.BooleanField(help_text="Whether the service is healthy")),
                (
                    "response_time_ms",
                    models.FloatField(blank=True, help_text="Response time in milliseconds", null=True),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, help_text="Error message if check failed", null=True),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional metadata about the health check"
                    ),
                ),
                (
                    "checked_at",
                    models.DateTimeField(auto_now_add=True, help_text="When the health check was performed"),
                ),
            ],
            options={
                "verbose_name": "System Health Check",
                "verbose_name_plural": "System Health Checks",
                "ordering": ["-checked_at"],
            },
        ),
    ]
