[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid
stdout_events_enabled=true  # Enable logging to the terminal

[program:uvicorn]
command=/app/deploy/shell_scripts/uvicorn_start.sh
directory=/app
process_name=uvicorn_%(process_num)02d
autostart=true
autorestart=true
startretries=5
stdout_logfile=/var/log/supervisor/uvicorn.log
stderr_logfile=/var/log/supervisor/uvicorn_error.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=5
stderr_logfile_maxbytes=10MB
stderr_logfile_backups=5

# [program:celery-worker]
# command=/app/deploy/shell_scripts/celery_start.sh
# directory=/app
# numprocs=%(ENV_celery_workers)s  # Starts multiple Celery worker processes
# process_name=celery_worker_%(process_num)s
# autostart=true
# autorestart=true
# startretries=5
# stdout_logfile=/var/log/supervisor/celery_worker_%(process_num)s.log
# stderr_logfile=/var/log/supervisor/celery_worker_%(process_num)s_error.log
# stdout_logfile_maxbytes=10MB
# stdout_logfile_backups=5
# stderr_logfile_maxbytes=10MB
# stderr_logfile_backups=5

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock
