# Generated by Django 4.2.16 on 2025-12-15 13:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, help_text="Creation timestamp")),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="Last update timestamp")),
                (
                    "trace_id",
                    models.UUIDField(
                        blank=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="A UUID used for distributed tracing across services (e.g., OpenTelemetry span/trace ID).",
                        null=True,
                    ),
                ),
                (
                    "correlation_id",
                    models.CharField(
                        blank=True,
                        help_text="A generic identifier (e.g., request ID) linking related log entries, often across different parts of a single transaction.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "actor_id",
                    models.CharField(
                        blank=True,
                        help_text="ID of the user who performed the action",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "actor_email",
                    models.CharField(
                        blank=True,
                        help_text="Email of the user who performed the action",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="Action performed (e.g., CREATE, UPDATE, DELETE, LOGIN, PERMISSION_GRANT, STATE_CHANGE)",
                        max_length=50,
                    ),
                ),
                (
                    "target_model",
                    models.CharField(
                        help_text="Model path of the modified object (e.g. 'apps.animals.Animal')",
                        max_length=255,
                    ),
                ),
                ("target_object_id", models.CharField(help_text="ID of the modified object", max_length=255)),
                (
                    "object_representation",
                    models.TextField(
                        blank=True,
                        help_text="A string representation of the modified object (e.g., its name or title)",
                        null=True,
                    ),
                ),
                (
                    "changes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON diff of changes (standard format: {'field': {'old': 'val', 'new': 'val'}})",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(blank=True, help_text="IP address of the actor", null=True),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, help_text="User Agent string of the actor", null=True),
                ),
                (
                    "session_key",
                    models.CharField(
                        blank=True,
                        help_text="The session key associated with the action, useful for forensic linking",
                        max_length=40,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log Entry",
                "verbose_name_plural": "Audit Log Entries",
                "db_table": "audit_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["target_model", "target_object_id"], name="audit_logs_target__34cf9a_idx"
                    ),
                    models.Index(fields=["action"], name="audit_logs_action_31f574_idx"),
                    models.Index(fields=["actor_id"], name="audit_logs_actor_i_0badd2_idx"),
                    models.Index(fields=["actor_email"], name="audit_logs_actor_e_f3ef0d_idx"),
                    models.Index(fields=["created_at"], name="audit_logs_created_262184_idx"),
                    models.Index(fields=["correlation_id"], name="audit_logs_correla_953e51_idx"),
                ],
            },
        ),
    ]
