# Generated by Django 4.2.16 on 2025-11-30 07:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
                ('actor_id', models.CharField(blank=True, help_text='ID of the user who performed the action', max_length=255, null=True)),
                ('actor_email', models.CharField(blank=True, help_text='Email of the user who performed the action', max_length=255, null=True)),
                ('action', models.CharField(help_text='Action performed (e.g., CREATE, UPDATE, DELETE)', max_length=50)),
                ('target_model', models.CharField(help_text="Model path of the modified object (e.g. 'apps.animals.Animal')", max_length=255)),
                ('target_object_id', models.CharField(help_text='ID of the modified object', max_length=255)),
                ('changes', models.JSONField(blank=True, default=dict, help_text='JSON diff of changes (before/after)')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the actor', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User Agent string of the actor', null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['target_model', 'target_object_id'], name='apps_audit__target__1be23c_idx'), models.Index(fields=['action'], name='apps_audit__action_883bc8_idx'), models.Index(fields=['actor_id'], name='apps_audit__actor_i_3666eb_idx'), models.Index(fields=['actor_email'], name='apps_audit__actor_e_c384ee_idx'), models.Index(fields=['created_at'], name='apps_audit__created_2882a1_idx')],
            },
        ),
    ]
