# Generated by Django 4.2.16 on 2025-12-15 17:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Animal",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, help_text="Creation timestamp")),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="Last update timestamp")),
                ("name", models.CharField(max_length=100)),
                ("species", models.CharField(max_length=50)),
                ("age", models.IntegerField()),
            ],
            options={
                "db_table": "animals",
            },
        ),
    ]
